package com.zytc.demo.mapper;

import com.zytc.demo.entity.User;
import com.zytc.demo.entity.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zytc_user
     *
     * @mbg.generated Sat Oct 17 09:20:48 CST 2020
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zytc_user
     *
     * @mbg.generated Sat Oct 17 09:20:48 CST 2020
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zytc_user
     *
     * @mbg.generated Sat Oct 17 09:20:48 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zytc_user
     *
     * @mbg.generated Sat Oct 17 09:20:48 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zytc_user
     *
     * @mbg.generated Sat Oct 17 09:20:48 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zytc_user
     *
     * @mbg.generated Sat Oct 17 09:20:48 CST 2020
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zytc_user
     *
     * @mbg.generated Sat Oct 17 09:20:48 CST 2020
     */
    User selectByName(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zytc_user
     *
     * @mbg.generated Sat Oct 17 09:20:48 CST 2020
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zytc_user
     *
     * @mbg.generated Sat Oct 17 09:20:48 CST 2020
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zytc_user
     *
     * @mbg.generated Sat Oct 17 09:20:48 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zytc_user
     *
     * @mbg.generated Sat Oct 17 09:20:48 CST 2020
     */
    int updateByPrimaryKey(User record);
}