package com.zytc.demo.entity;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zytc_role.role_id
     *
     * @mbg.generated Sat Oct 17 09:22:41 CST 2020
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zytc_role.role_name
     *
     * @mbg.generated Sat Oct 17 09:22:41 CST 2020
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zytc_role.role_id
     *
     * @return the value of zytc_role.role_id
     *
     * @mbg.generated Sat Oct 17 09:22:41 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zytc_role.role_id
     *
     * @param roleId the value for zytc_role.role_id
     *
     * @mbg.generated Sat Oct 17 09:22:41 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zytc_role.role_name
     *
     * @return the value of zytc_role.role_name
     *
     * @mbg.generated Sat Oct 17 09:22:41 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zytc_role.role_name
     *
     * @param roleName the value for zytc_role.role_name
     *
     * @mbg.generated Sat Oct 17 09:22:41 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
}