package com.zytc.demo.entity;

public class UserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zytc_user_role.ur_id
     *
     * @mbg.generated Sat Oct 17 09:22:41 CST 2020
     */
    private Integer urId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zytc_user_role.user_id
     *
     * @mbg.generated Sat Oct 17 09:22:41 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zytc_user_role.role_id
     *
     * @mbg.generated Sat Oct 17 09:22:41 CST 2020
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zytc_user_role.ur_id
     *
     * @return the value of zytc_user_role.ur_id
     *
     * @mbg.generated Sat Oct 17 09:22:41 CST 2020
     */
    public Integer getUrId() {
        return urId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zytc_user_role.ur_id
     *
     * @param urId the value for zytc_user_role.ur_id
     *
     * @mbg.generated Sat Oct 17 09:22:41 CST 2020
     */
    public void setUrId(Integer urId) {
        this.urId = urId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zytc_user_role.user_id
     *
     * @return the value of zytc_user_role.user_id
     *
     * @mbg.generated Sat Oct 17 09:22:41 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zytc_user_role.user_id
     *
     * @param userId the value for zytc_user_role.user_id
     *
     * @mbg.generated Sat Oct 17 09:22:41 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zytc_user_role.role_id
     *
     * @return the value of zytc_user_role.role_id
     *
     * @mbg.generated Sat Oct 17 09:22:41 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zytc_user_role.role_id
     *
     * @param roleId the value for zytc_user_role.role_id
     *
     * @mbg.generated Sat Oct 17 09:22:41 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}