package com.zytc.demo.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zytc_user.id
     *
     * @mbg.generated Sat Oct 17 09:20:48 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zytc_user.user_name
     *
     * @mbg.generated Sat Oct 17 09:20:48 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zytc_user.user_password
     *
     * @mbg.generated Sat Oct 17 09:20:48 CST 2020
     */
    private String userPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zytc_user.id
     *
     * @return the value of zytc_user.id
     *
     * @mbg.generated Sat Oct 17 09:20:48 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zytc_user.id
     *
     * @param id the value for zytc_user.id
     *
     * @mbg.generated Sat Oct 17 09:20:48 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zytc_user.user_name
     *
     * @return the value of zytc_user.user_name
     *
     * @mbg.generated Sat Oct 17 09:20:48 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zytc_user.user_name
     *
     * @param userName the value for zytc_user.user_name
     *
     * @mbg.generated Sat Oct 17 09:20:48 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zytc_user.user_password
     *
     * @return the value of zytc_user.user_password
     *
     * @mbg.generated Sat Oct 17 09:20:48 CST 2020
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zytc_user.user_password
     *
     * @param userPassword the value for zytc_user.user_password
     *
     * @mbg.generated Sat Oct 17 09:20:48 CST 2020
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
}